import './HeaderFooter.css'
function Footer() {
    return (
    <>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <div className="Footer">
            <p>*Patch Notes are generated by AI and therefore may be inaccurate or outdated. Always verify the information before relying on it.</p>
        </div>
        
    </>
    )
    }

export default Footer;