import './HeaderFooter.css'

function Footer() {
    return (
        <div className="Footer">
            <p>*Patch Notes are generated by AI and therefore may be inaccurate or outdated. Always verify the information before relying on it.</p>
        </div>
    );
}

export default Footer;
